### ISSUE TITLE
When Booking an Event

### ISSUE THREAD

**Issue by chrisrocco** [vector-web-development/tcc-server#7]
"Type error: Argument 1 passed to App\Services\PricingService::getPromotions() must be an instance of Carbon\Carbon or null, string given, called in /var/www/tcc-server-dev/app/Http/Controllers/EventController.php on line 104"

**Comment by cfalcione** [comment]
Fixed in https://github.com/vector-web-development/tcc-server/commit/b179738f41e5846531ab65650650bb626cc05b91
